version: '3.3' 
services:
  demo.db: 
    image: mysql:8.0 
    command: --default-authentication-plugin=mysql_native_password --log-error=/var/lib/mysql/error.log --general-log=ON --general-log-file=/var/lib/mysql/general.log --slow-query-log=ON --slow-query-log-file=/var/lib/mysql/slow.log --log-output=FILE 
    container_name: demo.db 
    restart: always 
    environment: 
      MYSQL_ROOT_PASSWORD: 123456 
      MYSQL_USER: "admin" 
      MYSQL_PASSWORD: "goodday"
    volumes:
      - ./mysql_custom_system:/var/lib/mysql
      # new MYSQL_DATABASE will trigger below files be imported by default to the database specified
      #- ./mysql_auto_import_folder:/docker-entrypoint-initdb.d
      - ./mysql_custom_configuration_80:/etc/mysql/conf.d
    ports:
      - 33072:3306 
  demo.adminer:
    image: adminer 
    container_name: demo.adminer 
    depends_on:
      - demo.db 
    restart: always 
    ports: 
      - 17184:8080 
    environment: 
      MYSQL_USERNAME: root 
      MYSQL_ROOT_PASSWORD: 123456 
      PMA_HOST: demo.db 
  demo.redis: 
    image: redis:6.0 
    container_name: demo.redis 
  demo.php-api: 
    #build: ./env/nginx-php-fpm-74 
    image: "php-fpm-nginx:7.4-modify" 
    container_name: demo.php-api 
    volumes: 
      - ./nginx_common_webs:/usr/share/nginx/html 
      - ./php_custom_nginx_conf:/etc/nginx/sites-available
      ## php-fpm
      #- ./project:/var/www/html
      ## php-cli
      - ../service:/opt/service
    ports: 
      - 18440:80 
      - 18441:8000 

networks: 
  default: 
    external: 
      name: demo-bridge 

