version: '3.3' 
services:
  fruit.db: 
    image: mysql:8.0 
    command: --default-authentication-plugin=mysql_native_password 
    container_name: fruit.db 
    restart: always 
    environment: 
      MYSQL_ROOT_PASSWORD: 123456 
      MYSQL_USER: "admin" 
      MYSQL_PASSWORD: "goodday"
    volumes:
      - ./mysql_custom_system:/var/lib/mysql
      # new MYSQL_DATABASE will trigger below files be imported by default to the database specified
      #- ./mysql_auto_import_folder:/docker-entrypoint-initdb.d
      - ./mysql_custom_configuration_80:/etc/mysql/conf.d
    ports:
      - 33072:3306 
  fruit.adminer:
    image: adminer 
    container_name: fruit.adminer 
    depends_on:
      - fruit.db 
    restart: always 
    ports: 
      - 17184:8080 
    environment: 
      MYSQL_USERNAME: root 
      MYSQL_ROOT_PASSWORD: 123456 
      PMA_HOST: fruit.db 
  fruit.redis: 
    image: redis:6.0 
    container_name: fruit.redis 
  fruit.php-api: 
    #build: ./env/nginx-php-fpm-74 
    image: "php-fpm-nginx:7.4-modify" 
    container_name: fruit.php-api 
    volumes: 
      - ./php_custom_final_web:/usr/share/nginx/html 
      - ./php_custom_nginx_conf:/etc/nginx/sites-enabled 
      - ./api:/opt/app
    ports: 
      - 18440:80 
      
networks: 
  default: 
    external: 
      name: fruit-bridge 

